config/routes.rb
Rails.application.routes.draw do
  resources :deaths
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  resources :users, only: [:show]
  resources :scolarites
  resources :mbtis
  resources :formations
  resources :recommandations
  resources :contacts, only: [:new, :create]

 resources :profil_psychos

  resources :deaths do
    match '/scrape', to: 'deaths#scrape', via: :post, on: :collection
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  include MailForm::Delivery
  attribute :name,     :validate => true
  attribute :email,     :validate => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  attribute :sujet,     :validate => true
  attribute :message,     :validate => true

  def headers
    {
        :subject => "Formulaire de contact",
        :to => "edgar.bekier@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/death.rb
class Death < ApplicationRecord
end

app/models/deaths_spider.rb
class DeathSpider < Kimurai::Base
  @name = 'deaths_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//table>tbody>tr>td").each do |death|
      item = {}

      item[:title]      = death.css('a.blue-hover>span').text
      item[:age]      = death.css('a.blue-hover>span.age').text
      item[:lieu] = death.css('span.blue-hover').text

      Death.where(item).first_or_create
    end
  end
end

app/models/formation.rb
class Formation < ApplicationRecord
end

app/models/mbti.rb
class Mbti < ApplicationRecord
  belongs_to :user
end

app/models/profil_psycho.rb
class ProfilPsycho < ApplicationRecord
end

app/models/scolarite.rb
class Scolarite < ApplicationRecord
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :fullname, presence:true, length: {maximum: 50}

  has_many :scolarites
  has_many :mbtis

#  after_create :send_admin_mail
#  def send_admin_mail
#    UserNotifierMailer.send_signup_email(self).deliver
#  end

end

app/controllers/deaths_controller.rb
class DeathsController < InheritedResources::Base

  def index
    @deaths = Death.all
  end


  def scrape
    require 'openssl'
    require 'open-uri'
    doc = Nokogiri::HTML(open('https://www.simplifia.fr/avis-de-deces/derniers-avis-de-deces-publies'))

    entries = doc.css('.card')
    rate = entries.css('table')[0].css('tr')[1].css('td')[1].text
    @formattedrate = rate
    render template: 'deaths/scrape'
  end

  private

    def death_params
      params.require(:death).permit(:Name, :Age, :Lieu)
    end

end

app/controllers/mbtis_controller.rb
class MbtisController < ApplicationController

  before_action :set_mbti, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @mbtis = current_user.mbtis
  end

  def show
    @mbti = current_user.mbtis.build
  end

  def create
    @mbti = current_user.mbtis.build(mbti_params)
    if @mbti.save
      redirect_to @mbti, notice:"Votre mbti a été ajoutée avec succés"
    else
      render :new
    end
  end

  def new
    @mbti = current_user.mbtis.build
  end

  def edit

  end

  def update
    if @mbti.update(mbti_params)
      redirect_to @mbti, notice:"Modification enregistrée..."
    else
      render :edit
    end
  end

  def destroy
    @mbti.destroy
    redirect_to mbtis_path, danger: "Article supprimer avec succès"
  end

  private
  def set_mbti
    @mbti = Mbti.find(params[:id])
  end

  def mbti_params
    params.require(:mbti).permit(:question1, :question2, :question3, :question4, :question5, :question6, :question7, :question8, :question9, :question10)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    require 'openssl'
    require 'open-uri'
    doc = Nokogiri::HTML(open('https://www.simplifia.fr/avis-de-deces/derniers-avis-de-deces-publies'))

    @entries = doc.css('a.blue-hover')


#    @entries.each do |rate|
#      @death = {
#          nom: rate.css('span').text
#      }

#   end

#    @formattedrate = @death[:nom]
  end

  def scrape

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def create
    # Create the user from params
    @user = User.new(user_params)
    if @user.save
      # Deliver the signup email
      UserNotifierMailer.send_signup_email(@user).deliver
      redirect_to(@user, :notice => 'User created')
    else
      redirect_to new_user_registration_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :email, :fullname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deaths_helper.rb
module DeathsHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/mbtis_helper.rb
module MbtisHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profil_psychos_helper.rb
module ProfilPsychosHelper
end

app/helpers/scolarites_helper.rb
module ScolaritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/deaths/_form.html.erb
<%= form_with(model: death, local: true) do |form| %>
  <% if death.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(death.errors.count, "error") %> prohibited this death from being saved:</h2>

      <ul>
      <% death.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name, id: :death_Name %>
  </div>

  <div class="field">
    <%= form.label :Age %>
    <%= form.text_field :Age, id: :death_Age %>
  </div>

  <div class="field">
    <%= form.label :Lieu %>
    <%= form.text_field :Lieu, id: :death_Lieu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/deaths/edit.html.erb
<h1>Editing Death</h1>

<%= render 'form', death: @death %>

<%= link_to 'Show', @death %> |
<%= link_to 'Back', deaths_path %>

app/views/deaths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deaths</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Lieu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deaths.each do |death| %>
      <tr>
        <td><%= death.Name %></td>
        <td><%= death.Age %></td>
        <td><%= death.Lieu %></td>
        <td><%= link_to 'Show', death %></td>
        <td><%= link_to 'Edit', edit_death_path(death) %></td>
        <td><%= link_to 'Destroy', death, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Death', new_death_path %>

app/views/deaths/new.html.erb
<h1>New Death</h1>

<%= render 'form', death: @death %>

<%= link_to 'Back', deaths_path %>

app/views/deaths/scrape.html.erb
<%= link_to 'Retour', root_path %>

app/views/mbtis/_form.html.erb
<%= form_for @mbti do |f| %>
  <label>Est-il plutôt : A) Facile de vous connaitre, ou B) difficile de vous connaitre ?</label><br>
  <%= f.select :question1, [["A","A"],["B","B"]], id: "question1", prompt:"A Selectionner", class:"form-control" %>
  <br>
  <label>En accomplissant une tache, avez-vous tendance à A) commencer tôt, de manière à pouvoir terminer en avance, ou B) travailler plus rapidement à la dernière minute?</label><br>
  <%= f.select :question2, [["A","A"],["B","B"]], id: "question2", prompt:"A Selectionner", class:"form-control" %>
  <br>
  <label>Trouvez-vous  A) qu'il vous est facile de parler à pratiquement tout le monde aussi longtemps qu'il le faut, ou B) que vous n'avez pas beaucoup de choses à dire à certaines personnes dans certaines circonstances ?</label><br>
  <%= f.select :question3, [["A","A"],["B","B"]], id: "question3", prompt:"A Selectionner", class:"form-control" %>
  <br>
  <label>Préferez-vous que l'on vous considère comme quelqu'un de  A) pratique, ou B) d'ingénieux ?</label><br>
  <%= f.select :question4, [["A","A"],["B","B"]], id: "question4", prompt:"A Selectionner", class:"form-control" %>
  <br>
  <label>Etes-vous généralement  A) sociable et ouvert, ou B) plutôt discret et réservé ?</label><br>
  <%= f.select :question5, [["A","A"],["B","B"]], id: "question5", prompt:"A Selectionner", class:"form-control" %>
  <br>
  <label>Est-ce un plus beau compliment, de dire de quelqu'un qu'il est doué de  A) visoin, ou B) bon sens ?</label><br>
  <%= f.select :question6, [["A","A"],["B","B"]], id: "question6", prompt:"A Selectionner", class:"form-control" %>
<br>
  <label>Pretez-vous davantage attention A) aux sentiments des gens, ou B) à leurs droits ?</label><br>
  <%= f.select :question7, [["A","A"],["B","B"]], id: "question7", prompt:"A Selectionner", class:"form-control" %>
<br>
  <label>A une soirée, aimez-vous A) aider à ce que ça bouge, ou B) laisser les autres s'amuser à leur manière ?</label><br>
  <%= f.select :question8, [["A","A"],["B","B"]], id: "question8", prompt:"A Selectionner", class:"form-control" %>
  <br>
  <label>En général, préférez-vous A) Organiser vos rendez-vous à l'avance, ou B) être libre de faire ce que vous désirez sous l'impulsion du moment ?</label><br>
  <%= f.select :question9, [["A","A"],["B","B"]], id: "question9", prompt:"A Selectionner", class:"form-control" %>
  <br>
  <label>Lorsque vous êtes avec vos amis parlez-vous A) plus que les autres, ou B) moins que les autres ?</label><br>
  <%= f.select :question10, [["A","A"],["B","B"]], id: "question10", prompt:"A Selectionner", class:"form-control" %>


<br><br>
  <%= f.submit "Je valide mon questionnaire", class:"btn btn-primary" %>

<% end %>

app/views/mbtis/edit.html.erb
<%= render 'form' %>

app/views/mbtis/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to 'Profil', user_path(current_user.id) %></li>
      <li class="sidebar-item"><%= link_to 'Ma scolarité', scolarites_path %></li>
      <li class="sidebar-item"><%= link_to 'Mon profil MBTI', mbti_path(current_user.id) %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> Ma scolarité</div>
      <div class="panel-body">
        <% @mbtis.each do |mbti| %>
          <div class="col-md-9">
            <p>Question 1 : <%= mbti.question1 %></p>
            <p>Question 2 : <%= mbti.question2 %></p>
            <p>Question 3 : <%= mbti.question3 %></p>
            <p>Question 4 : <%= mbti.question4 %></p>
            <p>Question 5 : <%= mbti.question5 %></p>
            <p>Question 6 : <%= mbti.question6 %></p>
            <p>Question 7 : <%= mbti.question7 %></p>
            <p>Question 8 : <%= mbti.question8 %></p>
            <p>Question 9 : <%= mbti.question9 %></p>
            <p>Question 10 : <%= mbti.question10 %></p>

            <% if mbti.question1 == 'A' && mbti.question2 == 'B' %>
              <h3>Résultat : ENFJ</h3>
            <% else %>
              <h3>Résultat : ENFP</h3>
            <% end %>
          </div>
          <div class="col-md-3 right">
            <%= link_to 'Modifier mon MBTI', edit_mbti_path(mbti), class:"btn btn-primary" %><br>
            <%= link_to 'Supprimer', mbti_path(mbti), class:"btn btn-primary", :method => :delete %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/mbtis/new.html.erb
<%= render 'form' %>