config/routes.rb
Rails.application.routes.draw do
  resources :deaths
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  resources :users, only: [:show]
  resources :scolarites
  resources :mbtis
  resources :formations
  resources :recommandations
  resources :contacts, only: [:new, :create]

 resources :profil_psychos

  resources :deaths do
    match '/scrape', to: 'deaths#scrape', via: :post, on: :collection
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  include MailForm::Delivery
  attribute :name,     :validate => true
  attribute :email,     :validate => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  attribute :sujet,     :validate => true
  attribute :message,     :validate => true

  def headers
    {
        :subject => "Formulaire de contact",
        :to => "edgar.bekier@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/death.rb
class Death < ApplicationRecord
end

app/models/deaths_spider.rb
class DeathSpider < Kimurai::Base
  @name = 'deaths_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//table>tbody>tr>td").each do |death|
      item = {}

      item[:title]      = death.css('a.blue-hover>span').text
      item[:age]      = death.css('a.blue-hover>span.age').text
      item[:lieu] = death.css('span.blue-hover').text

      Death.where(item).first_or_create
    end
  end
end

app/models/formation.rb
class Formation < ApplicationRecord
end

app/models/mbti.rb
class Mbti < ApplicationRecord
  belongs_to :user
end

app/models/profil_psycho.rb
class ProfilPsycho < ApplicationRecord
end

app/models/scolarite.rb
class Scolarite < ApplicationRecord
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :fullname, presence:true, length: {maximum: 50}

  has_many :scolarites
  has_many :mbtis

#  after_create :send_admin_mail
#  def send_admin_mail
#    UserNotifierMailer.send_signup_email(self).deliver
#  end

end

app/controllers/ap1/v1/scolarites_controller.rb
module Api
  module V1
    class ScolaritesController < ApplicationController
      def index
        @scolarites = Scolarite.all
        render json: @scolarites
      end
    end
  end
end

app/controllers/deaths_controller.rb
class DeathsController < InheritedResources::Base

  def index
    @deaths = Death.all
  end


  def scrape
    require 'openssl'
    require 'open-uri'
    doc = Nokogiri::HTML(open('https://www.simplifia.fr/avis-de-deces/derniers-avis-de-deces-publies'))

    entries = doc.css('.card')
    rate = entries.css('table')[0].css('tr')[1].css('td')[1].text
    @formattedrate = rate
    render template: 'deaths/scrape'
  end

  private

    def death_params
      params.require(:death).permit(:Name, :Age, :Lieu)
    end

end

app/controllers/mbtis_controller.rb
class MbtisController < ApplicationController

  before_action :set_mbti, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @mbtis = current_user.mbtis
  end

  def show
    @mbti = current_user.mbtis.build
  end

  def create
    @mbti = current_user.mbtis.build(mbti_params)
    if @mbti.save
      redirect_to @mbti, notice:"Votre mbti a été ajoutée avec succés"
    else
      render :new
    end
  end

  def new
    @mbti = current_user.mbtis.build
  end

  def edit

  end

  def update
    if @mbti.update(mbti_params)
      redirect_to @mbti, notice:"Modification enregistrée..."
    else
      render :edit
    end
  end

  def destroy
    @mbti.destroy
    redirect_to mbtis_path, danger: "Article supprimer avec succès"
  end

  private
  def set_mbti
    @mbti = Mbti.find(params[:id])
  end

  def mbti_params
    params.require(:mbti).permit(:question1, :question2, :question3, :question4, :question5, :question6, :question7, :question8, :question9, :question10)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    require 'openssl'
    require 'open-uri'
    doc = Nokogiri::HTML(open('https://www.simplifia.fr/avis-de-deces/derniers-avis-de-deces-publies'))

    @entries = doc.css('a.blue-hover')


#    @entries.each do |rate|
#      @death = {
#          nom: rate.css('span').text
#      }

#   end

#    @formattedrate = @death[:nom]
  end

  def scrape

  end

end

app/controllers/scolarites_controller.rb
class ScolaritesController < ApplicationController

      before_action :set_scolarite, only: [:show, :edit, :update, :destroy]
      before_action :authenticate_user!, except: [:show]

      def index
        @scolarites = current_user.scolarites
      end

      def api
        @scolarites = Scolarite.all
        render json: @scolarites
      end

      def show
        @scolarite = current_user.scolarites.build
      end

      def create
        @scolarite = current_user.scolarites.build(scolarite_params)
        if @scolarite.save
          redirect_to @scolarite, notice:"Votre scolarite a été ajoutée avec succés"
        else
          render :new
        end
      end

      def new
        @scolarite = current_user.scolarites.build
      end

      def edit

      end

      def update
        if @scolarite.update(scolarite_params)
          redirect_to @scolarite, notice:"Modification enregistrée..."
        else
          render :edit
        end
      end

      def destroy
        @scolarite.destroy
        redirect_to scolarites_path, danger: "Article supprimer avec succès"
      end

      private
      def set_scolarite
        @scolarite = Scolarite.find(params[:id])
      end

      def scolarite_params
        params.require(:scolarite).permit(:filiere, :francais, :philosophie, :histoiregeo, :lv1, :lv2, :eps, :mathematique, :physiquechimie, :svt, :ses, :spemath, :spesvt, :spephysique, :tpe, :lv3)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def create
    # Create the user from params
    @user = User.new(user_params)
    if @user.save
      # Deliver the signup email
      UserNotifierMailer.send_signup_email(@user).deliver
      redirect_to(@user, :notice => 'User created')
    else
      redirect_to new_user_registration_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :email, :fullname)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deaths_helper.rb
module DeathsHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/mbtis_helper.rb
module MbtisHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scolarites_helper.rb
module ScolaritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/scolarites/_form.html.erb
<%= form_for @scolarite do |f| %>
  <label>Filière</label>
  <%= f.select :filiere, [["S","S"],["ES","ES"],["L","L"]], id: "filiere", prompt:"A Selectionner", class:"form-control" %>

  <%= f.text_field :francais, placeholder:"Français", class:"form-group" %>
  <%= f.text_field :philosophie, placeholder:"philosophie", class:"form-group" %>
  <%= f.text_field :histoiregeo, placeholder:"histoiregeo", class:"form-group" %>
  <%= f.text_field :lv1, placeholder:"lv1", class:"form-group" %>
  <%= f.text_field :lv2, placeholder:"lv2", class:"form-group" %>
  <%= f.text_field :eps, placeholder:"eps", class:"form-group" %>
  <%= f.text_field :mathematique, placeholder:"mathematique", class:"form-group" %>
  <%= f.text_field :physiquechimie, placeholder:"physiquechimie", class:"form-group" %>
  <%= f.text_field :svt, placeholder:"svt", class:"form-group" %>
  <%= f.text_field :ses, placeholder:"ses", class:"form-group" %>
  <%= f.text_field :spemath, placeholder:"spemath", class:"form-group" %>
  <%= f.text_field :spesvt, placeholder:"spesvt", class:"form-group" %>
  <%= f.text_field :spephysique, placeholder:"spephysique", class:"form-group" %>
  <%= f.text_field :tpe, placeholder:"tpe", class:"form-group" %>
  <%= f.text_field :lv3, placeholder:"lv3", class:"form-group" %>

  <%= f.submit "Je valide mes notes", class:"btn btn-primary" %>

<% end %>

app/views/scolarites/edit.html.erb
<% render 'form' %>

app/views/scolarites/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to 'Profil', user_path(current_user.id) %></li>
      <li class="sidebar-item"><%= link_to 'Ma scolarité', scolarites_path %></li>
      <li class="sidebar-item"><%= link_to 'Mon profil MBTI', mbtis_path %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> Ma scolarité</div>
      <div class="panel-body">
        <% @scolarites.each do |scolarite| %>
        <div class="col-md-9">
          <p>Filière : <%= scolarite.filiere %></p>
          <p>Français : <%= scolarite.francais %></p>
          <p>Philosophie : <%= scolarite.philosophie %></p>
          <p>Histoire géographie<%= scolarite.histoiregeo %></p>
          <p>lv1 : <%= scolarite.lv1 %></p>
          <p>lv2 : <%= scolarite.lv2 %></p>
          <p>eps : <%= scolarite.eps %></p>
          <p>Mathématique : <%= scolarite.mathematique %></p>
          <p>Physique-chimie : <%= scolarite.physiquechimie %></p>
          <p>svt : <%= scolarite.svt %></p>
          <p>Sciences économiques et sociales : <%= scolarite.ses %></p>
          <p>spémath : <%= scolarite.spemath %></p>
          <p>spesvt : <%= scolarite.spesvt %></p>
          <p>spephysique : <%= scolarite.spephysique %></p>
          <p>TPE : <%= scolarite.tpe %></p>
          <p>lv3 : <%= scolarite.lv3 %></p>
        </div>
          <div class="col-md-3 right">
            <%= link_to 'Modifier ma scolarité', edit_scolarite_path(scolarite), class:"btn btn-primary" %><br>
            <%= link_to 'Supprimer', scolarite_path(scolarite), class:"btn btn-primary", :method => :delete %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>