config/routes.rb
Rails.application.routes.draw do
  resources :deaths
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  resources :users, only: [:show]
  resources :scolarites
  resources :mbtis
  resources :formations
  resources :recommandations
  resources :contacts, only: [:new, :create]

 resources :profil_psychos

  resources :deaths do
    match '/scrape', to: 'deaths#scrape', via: :post, on: :collection
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  include MailForm::Delivery
  attribute :name,     :validate => true
  attribute :email,     :validate => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  attribute :sujet,     :validate => true
  attribute :message,     :validate => true

  def headers
    {
        :subject => "Formulaire de contact",
        :to => "edgar.bekier@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/death.rb
class Death < ApplicationRecord
end

app/models/deaths_spider.rb
class DeathSpider < Kimurai::Base
  @name = 'deaths_spider'
  @engine = :mechanize

  def self.process(url)
    @start_urls = [url]
    self.crawl!
  end

  def parse(response, url:, data: {})
    response.xpath("//table>tbody>tr>td").each do |death|
      item = {}

      item[:title]      = death.css('a.blue-hover>span').text
      item[:age]      = death.css('a.blue-hover>span.age').text
      item[:lieu] = death.css('span.blue-hover').text

      Death.where(item).first_or_create
    end
  end
end

app/models/formation.rb
class Formation < ApplicationRecord
end

app/models/mbti.rb
class Mbti < ApplicationRecord
  belongs_to :user
end

app/models/profil_psycho.rb
class ProfilPsycho < ApplicationRecord
end

app/models/scolarite.rb
class Scolarite < ApplicationRecord
  belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :fullname, presence:true, length: {maximum: 50}

  has_many :scolarites
  has_many :mbtis

#  after_create :send_admin_mail
#  def send_admin_mail
#    UserNotifierMailer.send_signup_email(self).deliver
#  end

end

app/controllers/mbtis_controller.rb
class MbtisController < ApplicationController

  before_action :set_mbti, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @mbtis = current_user.mbtis
  end

  def show
    @mbti = current_user.mbtis.build
  end

  def create
    @mbti = current_user.mbtis.build(mbti_params)
    if @mbti.save
      redirect_to @mbti, notice:"Votre mbti a été ajoutée avec succés"
    else
      render :new
    end
  end

  def new
    @mbti = current_user.mbtis.build
  end

  def edit

  end

  def update
    if @mbti.update(mbti_params)
      redirect_to @mbti, notice:"Modification enregistrée..."
    else
      render :edit
    end
  end

  def destroy
    @mbti.destroy
    redirect_to mbtis_path, danger: "Article supprimer avec succès"
  end

  private
  def set_mbti
    @mbti = Mbti.find(params[:id])
  end

  def mbti_params
    params.require(:mbti).permit(:question1, :question2, :question3, :question4, :question5, :question6, :question7, :question8, :question9, :question10)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    require 'openssl'
    require 'open-uri'
    doc = Nokogiri::HTML(open('https://www.simplifia.fr/avis-de-deces/derniers-avis-de-deces-publies'))

    @entries = doc.css('a.blue-hover')


#    @entries.each do |rate|
#      @death = {
#          nom: rate.css('span').text
#      }

#   end

#    @formattedrate = @death[:nom]
  end

  def scrape

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deaths_helper.rb
module DeathsHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/mbtis_helper.rb
module MbtisHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scolarites_helper.rb
module ScolaritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">EDUCAIA</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Accueil', root_path %></li>
        <li><%= link_to 'Formations', formations_path %></li>
        <li><%= link_to 'Décès', deaths_path %></li>
        <li><%= link_to 'contact', new_contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %>
          <li><%= link_to 'Inscription', new_user_registration_path %></li>
          <li><%= link_to 'Connexion', new_user_session_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.fullname %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profil', user_path(current_user.id) %></li>
              <li><%= link_to 'Ma scolarite', scolarites_path %></li>
              <li><%= link_to 'Mon profil MBTI', mbtis_path %></li>
              <li><%= link_to 'Recommandations', recommandations_path %></li>
            </ul>
          </li>
          <li><%= link_to 'Modifier profil', edit_user_registration_path %></li>
          <li><%= link_to 'Deconnexion', destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Educaia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>

  <%= yield %>

  </body>
</html>